title: "Jules Malavieille"
description: "Modélisation mathématique en environnement marin"
url: "https://julesmalavieille.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

navigation:
  enabled: true

markdown: kramdown
kramdown:
  input: GFM

minimal_mistakes_skin: "dark"

collections:
  pages:
    output: true
    permalink: /:path/

header_pages:
  - index.md
  - pages/education.md
  - pages/mecanistic_modelisation.md
  - pages/bifurcation_theory.md
  -pages/ML_DL.md

sass:
  custom: "assets/css/custom.css"

