title: "Jules Malavieille"
description: "Modélisation mathématique en environnement marin"
url: "https://julesmalavieille.github.io"
baseurl: ""
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM

minimal_mistakes_skin: "dark"
